### ISSUE TITLE
Buildroot custom linux build for renode cortex-a series cpu

### ISSUE THREAD

**Issue by fly-lynx** [brempusz/buildroot_renode#1]
how to create a buildroot custom Linux for Cortex-A53 to run on RENODE?

**Comment by brempusz** [comment]
Unfortunately - I don't know.

I would start with https://github.com/buildroot/buildroot/tree/master/board/qemu/aarch64-virt and do something similar to what I did for RISCV: dump device tree from qemu and manually map it to renode configuration. 

Or you can ask renode authors for help (I did, but no answer so far... https://github.com/renode/renode/issues/638).
They know how to build custom kernel for cortex-a53, (https://github.com/renode/renode/blob/master/scripts/single-node/cortex-a53-linux.resc), maybe they can share the process?

**Comment by brempusz** [comment]
There is nothing I can add for now. Sorry :(.
